In [6]:
import numpy as np

In [7]:
A = np.matrix([[2, -3, 0],
               [1, 5, 19]])
print(np.dot(4, A))

[[  8 -12   0]
 [  4  20  76]]


In [8]:
A = np.matrix([[5, 1, 3]])
B = np.matrix([[2], 
               [4], 
               [6]])
print(np.dot(A, B))


[[32]]


In [9]:
A = np.matrix([[1, 3, 2],
               [4, 0, -1]])
B = np.matrix([[5, 10],
               [2, -2],
               [-3, 6]])
print(np.dot(A, B)) # dot product

[[ 5 16]
 [23 34]]


In [10]:
print(A * B) # dot product

[[ 5 16]
 [23 34]]


In [11]:
A = np.matrix([[3], [2]])
B = np.matrix([[5], [4]])
print(np.kron(A, B)) # Tensor product, kron refers to Kronecker

[[15]
 [12]
 [10]
 [ 8]]
